#coding=utf-8
data = [
    {
        'zh':u'老鼠',
        'en':'rat'
    },
    {
        'zh':u'牛',
        'en':'cattle'
    },
    {
        'zh':u'老虎',
        'en':'tiger'
    },
    {
        'zh':u'兔',
        'en':'rabbit'
    },
    {
        'zh':u'龙',
        'en':'dragon'
    },
    {
        'zh':u'蛇',
        'en':'snake'
    },
    {
        'zh':u'马',
        'en':'horse'
    },
    {
        'zh':u'羊',
        'en':'sheep'
    },
    {
        'zh':u'猴子',
        'en':'monkey'
    },
    {
        'zh':u'鸡',
        'en':'chicken'
    },
    {
        'zh':u'狗',
        'en':'dog'
    },
    {
        'zh':u'猪',
        'en':'pig'
    },
    {
        'zh':u'猫',
        'en':'cat'
    },
    {
        'zh':u'狮子',
        'en':'lion'
    },
    {
        'zh':u'猎豹',
        'en':'cheetah'
    },
    {
        'zh':u'狼',
        'en':'wolf'
    },
    {
        'zh':u'大象',
        'en':'elephant'
    },
    {
        'zh':u'长颈鹿',
        'en':'giraffe'
    },
    {
        'zh':u'燕子',
        'en':'swallow'
    },
    {
        'zh':u'企鹅',
        'en':'penguin'
    },
    {
        'zh':u'熊',
        'en':'bear'
    },
    {
        'zh':u'熊猫',
        'en':'panda'
    },
    {
        'zh':u'鳄鱼',
        'en':'crocodile'
    },
    {
        'zh':u'海豚',
        'en':'dolphin'
    },
    {
        'zh':u'鲸鱼',
        'en':'cetacea'
    },
    {
        'zh':u'鲨鱼',
        'en':'shark'
    },
    {
        'zh':u'虾',
        'en':'shrimp'
    },
    {
        'zh':u'螃蟹',
        'en':'crab'
    },
]