#coding=utf-8
data = [
    {
        'zh':u'爸爸',
        'en':'dad',
    },
    {
        'zh':u'妈妈',
        'en':'mom',
    },
    {
        'zh':u'爷爷',
        'en':'grandpa',
    },
    {
        'zh':u'奶奶',
        'en':'grandma',
    },
    {
        'zh':u'外公',
        'en':'grandfather',
    },
    {
        'zh':u'外婆',
        'en':'grandmother',
    },
    {
        'zh':u'哥哥',
        'en':'elder brother',
    },
    {
        'zh':u'姐姐',
        'en':'elder sister',
    },
    {
        'zh':u'弟弟',
        'en':'younger brother',
    },
    {
        'zh':u'妹妹',
        'en':'younger sister',
    },
    {
        'zh':u'叔叔',
        'en':'uncle',
    },
    {
        'zh':u'阿姨',
        'en':'aunt',
    },
    {
        'zh':u'老师',
        'en':'teacher',
    },
    {
        'zh':u'同学',
        'en':'classmate',
    },
    {
        'zh':u'朋友',
        'en':'friend',
    },
    {
        'zh':u'医生',
        'en':'doctor',
    },
    {
        'zh':u'科学家',
        'en':'scientist',
    },
    {
        'zh':u'消防员',
        'en':'fireman',
    },
]