#coding=utf-8
data = [
    {
        'zh':u'被子',
        'en':'quilt',
    },
    {
        'zh':u'枕头',
        'en':'pillow',
    },
    {
        'zh':u'帽子',
        'en':'hat',
    },
    {
        'zh':u'手套',
        'en':'gloves',
    },
    {
        'zh':u'毛巾',
        'en':'towel',
    },
    {
        'zh':u'拖鞋',
        'en':'slipper',
    },
    {
        'zh':u'鞋',
        'en':'shoes',
    },
    {
        'zh':u'牙刷',
        'en':'toothbrush',
    },
    {
        'zh':u'牙膏',
        'en':'toothpaste',
    },
    {
        'zh':u'镜子',
        'en':'mirror',
    },
    {
        'zh':u'梳子',
        'en':'comb',
    },
    {
        'zh':u'肥皂',
        'en':'soap',
    },
    {
        'zh':u'杯子',
        'en':'cup',
    },
    {
        'zh':u'碗',
        'en':'bowl',
    },
    {
        'zh':u'手机',
        'en':'mobile phone',
    },
    {
        'zh':u'电话',
        'en':'telephone',
    },
    {
        'zh':u'电脑',
        'en':'computer',
    },
    {
        'zh':u'电视机',
        'en':'television',
    },
    {
        'zh':u'雨伞',
        'en':'umbrella',
    },
    {
        'zh':u'足球',
        'en':'football',
    },
    {
        'zh':u'篮球',
        'en':'basketball',
    },
]