#coding=utf-8
data = [
    {
        'zh':u'苹果',
        'en':'apple',
    },
    {
        'zh':u'香蕉',
        'en':'banana',
    },
    {
        'zh':u'梨',
        'en':'pear',
    },
    {
        'zh':u'橙子',
        'en':'orange',
    },
    {
        'zh':u'西瓜',
        'en':'watermelon',
    },
    {
        'zh':u'草莓',
        'en':'strawberry',
    },
    {
        'zh':u'葡萄',
        'en':'grape',
    },
    {
        'zh':u'菠萝',
        'en':'pineapple',
    },
    {
        'zh':u'樱桃',
        'en':'cherry',
    },
    {
        'zh':u'桃子',
        'en':'peach',
    },
    {
        'zh':u'荔枝',
        'en':'litchi',
    },
    {
        'zh':u'杨桃',
        'en':'carambola',
    },
    {
        'zh':u'柠檬',
        'en':'lemon',
    },
    {
        'zh':u'木瓜',
        'en':'pawpaw',
    },
    {
        'zh':u'火龙果',
        'en':'pitaya',
    },
    {
        'zh':u'蓝莓',
        'en':'blueberry',
    },
]