#coding=utf-8
data = [
    {
        'zh':u'胡萝卜',
        'en':'carrot'
    },
    {
        'zh':u'蘑菇',
        'en':'mushroom'
    },
    {
        'zh':u'茄子',
        'en':'eggplant'
    },
    {
        'zh':u'西红柿',
        'en':'tomato'
    },
    {
        'zh':u'南瓜',
        'en':'pumpkin'
    },
    {
        'zh':u'白菜',
        'en':'cabbage'
    },
    {
        'zh':u'西兰花',
        'en':'broccoli'
    },
    {
        'zh':u'蒜',
        'en':'garlic'
    },
    {
        'zh':u'洋葱',
        'en':'onion'
    },
    {
        'zh':u'大葱',
        'en':'scallion'
    },
    {
        'zh':u'番薯',
        'en':'sweet potato'
    },
    {
        'zh':u'土豆',
        'en':'potato'
    },
    {
        'zh':u'辣椒',
        'en':'pepper'
    },
    {
        'zh':u'香菜',
        'en':'coriander'
    },
    {
        'zh':u'豌豆',
        'en':'pea'
    },
]