#coding=utf-8
data = [
    {
        'zh':u'星期一',
        'en':'Monday',
    },
    {
        'zh':u'星期二',
        'en':'Tuesday',
    },
    {
        'zh':u'星期三',
        'en':'Wednesday',
    },
    {
        'zh':u'星期四',
        'en':'Thursday',
    },
    {
        'zh':u'星期五',
        'en':'Friday',
    },
    {
        'zh':u'星期六',
        'en':'Saturday',
    },
    {
        'zh':u'星期日',
        'en':'Sunday',
    },
]